name: Run Composite

on:
  workflow_dispatch:
    inputs:
      bug_id:
        description: 'Bug ID to repair'
        required: true
        type: string

jobs:
  run-auto-code-rover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install auto-code-rover

      - name: Run AutoCodeRover
        run: |
          auto-code-rover repair --bug-id ${{ github.event.inputs.bug_id }}

      - name: Upload repair results
        uses: actions/upload-artifact@v2
        with:
          name: repair-results
          path: repair_results/